// Bulk export of llama.cpp / ggml integer enum constants into the
// _llama_native module's attribute namespace.
//
// The flat list of integer enum values is registered as plain module
// attributes rather than typed nb::enum_ classes — preserving the
// `inferna.llama.llama_cpp.LLAMA_VOCAB_TYPE_BPE` direct-attribute access
// pattern that callers depend on.

#include <nanobind/nanobind.h>

#include "llama.h"
#include "ggml.h"
#include "ggml-backend.h"

namespace nb = nanobind;

#define EXPORT(name) m.attr(#name) = (int) name

void register_enums(nb::module_& m) {
    // -------- ggml.h scalar / dimension constants --------
    EXPORT(GGML_DEFAULT_N_THREADS);
    EXPORT(GGML_MAX_DIMS);
    EXPORT(GGML_MAX_N_THREADS);
    EXPORT(GGML_MAX_NAME);
    EXPORT(GGML_MAX_OP_PARAMS);
    EXPORT(GGML_MAX_SRC);

    // -------- ggml RoPE type --------
    EXPORT(GGML_ROPE_TYPE_NEOX);
    EXPORT(GGML_ROPE_TYPE_MROPE);
    EXPORT(GGML_ROPE_TYPE_VISION);
    EXPORT(GGML_ROPE_TYPE_IMROPE);

    // -------- ggml NUMA strategy --------
    EXPORT(GGML_NUMA_STRATEGY_DISABLED);
    EXPORT(GGML_NUMA_STRATEGY_DISTRIBUTE);
    EXPORT(GGML_NUMA_STRATEGY_ISOLATE);
    EXPORT(GGML_NUMA_STRATEGY_NUMACTL);
    EXPORT(GGML_NUMA_STRATEGY_MIRROR);

    // -------- ggml log levels --------
    EXPORT(GGML_LOG_LEVEL_NONE);
    EXPORT(GGML_LOG_LEVEL_INFO);
    EXPORT(GGML_LOG_LEVEL_WARN);
    EXPORT(GGML_LOG_LEVEL_ERROR);
    EXPORT(GGML_LOG_LEVEL_DEBUG);
    EXPORT(GGML_LOG_LEVEL_CONT);

    // -------- ggml status --------
    EXPORT(GGML_STATUS_ALLOC_FAILED);
    EXPORT(GGML_STATUS_FAILED);
    EXPORT(GGML_STATUS_SUCCESS);
    EXPORT(GGML_STATUS_ABORTED);

    // -------- ggml dtype --------
    EXPORT(GGML_TYPE_F32);
    EXPORT(GGML_TYPE_F16);
    EXPORT(GGML_TYPE_Q4_0);
    EXPORT(GGML_TYPE_Q4_1);
    EXPORT(GGML_TYPE_Q5_0);
    EXPORT(GGML_TYPE_Q5_1);
    EXPORT(GGML_TYPE_Q8_0);
    EXPORT(GGML_TYPE_Q8_1);
    EXPORT(GGML_TYPE_Q2_K);
    EXPORT(GGML_TYPE_Q3_K);
    EXPORT(GGML_TYPE_Q4_K);
    EXPORT(GGML_TYPE_Q5_K);
    EXPORT(GGML_TYPE_Q6_K);
    EXPORT(GGML_TYPE_Q8_K);
    EXPORT(GGML_TYPE_IQ2_XXS);
    EXPORT(GGML_TYPE_IQ2_XS);
    EXPORT(GGML_TYPE_IQ3_XXS);
    EXPORT(GGML_TYPE_IQ1_S);
    EXPORT(GGML_TYPE_IQ4_NL);
    EXPORT(GGML_TYPE_IQ3_S);
    EXPORT(GGML_TYPE_IQ2_S);
    EXPORT(GGML_TYPE_IQ4_XS);
    EXPORT(GGML_TYPE_I8);
    EXPORT(GGML_TYPE_I16);
    EXPORT(GGML_TYPE_I32);
    EXPORT(GGML_TYPE_I64);
    EXPORT(GGML_TYPE_F64);
    EXPORT(GGML_TYPE_IQ1_M);
    EXPORT(GGML_TYPE_BF16);
    EXPORT(GGML_TYPE_TQ1_0);
    EXPORT(GGML_TYPE_TQ2_0);
    EXPORT(GGML_TYPE_MXFP4);
    EXPORT(GGML_TYPE_COUNT);

    // -------- ggml precision --------
    EXPORT(GGML_PREC_DEFAULT);
    EXPORT(GGML_PREC_F32);

    // -------- ggml op (only NONE used by callers) --------
    EXPORT(GGML_OP_NONE);

    // -------- ggml triangular --------
    EXPORT(GGML_TRI_TYPE_UPPER_DIAG);
    EXPORT(GGML_TRI_TYPE_UPPER);
    EXPORT(GGML_TRI_TYPE_LOWER_DIAG);
    EXPORT(GGML_TRI_TYPE_LOWER);

    // -------- ggml scale mode --------
    EXPORT(GGML_SCALE_MODE_NEAREST);
    EXPORT(GGML_SCALE_MODE_BILINEAR);
    EXPORT(GGML_SCALE_MODE_BICUBIC);

    // -------- ggml opt build type --------
    EXPORT(GGML_OPT_BUILD_TYPE_FORWARD);
    EXPORT(GGML_OPT_BUILD_TYPE_GRAD);
    EXPORT(GGML_OPT_BUILD_TYPE_OPT);

    // -------- ggml backend device type --------
    EXPORT(GGML_BACKEND_DEVICE_TYPE_CPU);
    EXPORT(GGML_BACKEND_DEVICE_TYPE_GPU);
    EXPORT(GGML_BACKEND_DEVICE_TYPE_IGPU);
    EXPORT(GGML_BACKEND_DEVICE_TYPE_ACCEL);
    EXPORT(GGML_BACKEND_DEVICE_TYPE_META);

    // -------- llama vocab type --------
    EXPORT(LLAMA_VOCAB_TYPE_NONE);
    EXPORT(LLAMA_VOCAB_TYPE_SPM);
    EXPORT(LLAMA_VOCAB_TYPE_BPE);
    EXPORT(LLAMA_VOCAB_TYPE_WPM);
    EXPORT(LLAMA_VOCAB_TYPE_UGM);
    EXPORT(LLAMA_VOCAB_TYPE_RWKV);
    EXPORT(LLAMA_VOCAB_TYPE_PLAMO2);

    // -------- llama RoPE type --------
    EXPORT(LLAMA_ROPE_TYPE_NONE);
    EXPORT(LLAMA_ROPE_TYPE_NORM);
    EXPORT(LLAMA_ROPE_TYPE_NEOX);
    EXPORT(LLAMA_ROPE_TYPE_MROPE);
    EXPORT(LLAMA_ROPE_TYPE_VISION);
    EXPORT(LLAMA_ROPE_TYPE_IMROPE);

    // -------- llama token type --------
    EXPORT(LLAMA_TOKEN_TYPE_UNDEFINED);
    EXPORT(LLAMA_TOKEN_TYPE_NORMAL);
    EXPORT(LLAMA_TOKEN_TYPE_UNKNOWN);
    EXPORT(LLAMA_TOKEN_TYPE_CONTROL);
    EXPORT(LLAMA_TOKEN_TYPE_USER_DEFINED);
    EXPORT(LLAMA_TOKEN_TYPE_UNUSED);
    EXPORT(LLAMA_TOKEN_TYPE_BYTE);

    // -------- llama token attr (bit flags) --------
    EXPORT(LLAMA_TOKEN_ATTR_UNDEFINED);
    EXPORT(LLAMA_TOKEN_ATTR_UNKNOWN);
    EXPORT(LLAMA_TOKEN_ATTR_UNUSED);
    EXPORT(LLAMA_TOKEN_ATTR_NORMAL);
    EXPORT(LLAMA_TOKEN_ATTR_CONTROL);
    EXPORT(LLAMA_TOKEN_ATTR_USER_DEFINED);
    EXPORT(LLAMA_TOKEN_ATTR_BYTE);
    EXPORT(LLAMA_TOKEN_ATTR_NORMALIZED);
    EXPORT(LLAMA_TOKEN_ATTR_LSTRIP);
    EXPORT(LLAMA_TOKEN_ATTR_RSTRIP);
    EXPORT(LLAMA_TOKEN_ATTR_SINGLE_WORD);

    // -------- llama ftype --------
    EXPORT(LLAMA_FTYPE_ALL_F32);
    EXPORT(LLAMA_FTYPE_MOSTLY_F16);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q4_0);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q4_1);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q8_0);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q5_0);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q5_1);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q2_K);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q3_K_S);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q3_K_M);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q3_K_L);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q4_K_S);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q4_K_M);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q5_K_S);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q5_K_M);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q6_K);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ2_XXS);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ2_XS);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q2_K_S);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ3_XS);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ3_XXS);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ1_S);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ4_NL);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ3_S);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ3_M);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ2_S);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ2_M);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ4_XS);
    EXPORT(LLAMA_FTYPE_MOSTLY_IQ1_M);
    EXPORT(LLAMA_FTYPE_MOSTLY_BF16);
    EXPORT(LLAMA_FTYPE_MOSTLY_TQ1_0);
    EXPORT(LLAMA_FTYPE_MOSTLY_TQ2_0);
    EXPORT(LLAMA_FTYPE_MOSTLY_MXFP4_MOE);
    EXPORT(LLAMA_FTYPE_MOSTLY_NVFP4);
    EXPORT(LLAMA_FTYPE_MOSTLY_Q1_0);
    EXPORT(LLAMA_FTYPE_GUESSED);

    // -------- llama RoPE scaling --------
    EXPORT(LLAMA_ROPE_SCALING_TYPE_UNSPECIFIED);
    EXPORT(LLAMA_ROPE_SCALING_TYPE_NONE);
    EXPORT(LLAMA_ROPE_SCALING_TYPE_LINEAR);
    EXPORT(LLAMA_ROPE_SCALING_TYPE_YARN);
    EXPORT(LLAMA_ROPE_SCALING_TYPE_LONGROPE);
    EXPORT(LLAMA_ROPE_SCALING_TYPE_MAX_VALUE);

    // -------- llama pooling --------
    EXPORT(LLAMA_POOLING_TYPE_UNSPECIFIED);
    EXPORT(LLAMA_POOLING_TYPE_NONE);
    EXPORT(LLAMA_POOLING_TYPE_MEAN);
    EXPORT(LLAMA_POOLING_TYPE_CLS);
    EXPORT(LLAMA_POOLING_TYPE_LAST);
    EXPORT(LLAMA_POOLING_TYPE_RANK);

    // -------- llama attention --------
    EXPORT(LLAMA_ATTENTION_TYPE_UNSPECIFIED);
    EXPORT(LLAMA_ATTENTION_TYPE_CAUSAL);
    EXPORT(LLAMA_ATTENTION_TYPE_NON_CAUSAL);

    // -------- llama flash attn --------
    EXPORT(LLAMA_FLASH_ATTN_TYPE_AUTO);
    EXPORT(LLAMA_FLASH_ATTN_TYPE_DISABLED);
    EXPORT(LLAMA_FLASH_ATTN_TYPE_ENABLED);

    // -------- llama split mode --------
    EXPORT(LLAMA_SPLIT_MODE_NONE);
    EXPORT(LLAMA_SPLIT_MODE_LAYER);
    EXPORT(LLAMA_SPLIT_MODE_ROW);
    EXPORT(LLAMA_SPLIT_MODE_TENSOR);

    // -------- llama token sentinel (preprocessor define) --------
    m.attr("LLAMA_TOKEN_NULL") = (int) LLAMA_TOKEN_NULL;
}

#undef EXPORT
