"""Loader for the auto-generated build_config.json.

``build_config.json`` is generated by ``manage.py`` at build time and
lives at the package root (``src/inferna/build_config.json``).  It is
``.gitignore``d but included in wheels.  This module provides a cached
accessor so consumers don't each need their own ``json.load`` + path
logic.
"""

from __future__ import annotations

import json
import os
from typing import Any

_cache: dict[str, Any] | None = None


def get() -> dict[str, Any]:
    """Return the build config dict, loading from disk on first call."""
    global _cache
    if _cache is not None:
        return _cache

    config_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "build_config.json")
    try:
        with open(config_path) as f:
            _cache = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        _cache = {"backend": {}, "versions": {}}
    return _cache


def backend() -> dict[str, Any]:
    """Return the ``backend`` section.

    Each backend is a dict with at least an ``enabled`` key::

        {"cuda": {"enabled": false, "architectures": null, ...}, ...}
    """
    backend_section: dict[str, Any] = get().get("backend", {})
    return backend_section


def backend_enabled(name: str) -> bool:
    """Return whether a specific backend was enabled at build time."""
    entry = backend().get(name, {})
    if isinstance(entry, dict):
        return bool(entry.get("enabled", False))
    return False


def versions() -> dict[str, str]:
    """Return the ``versions`` section (thirdparty version strings)."""
    versions_section: dict[str, str] = get().get("versions", {})
    return versions_section


def dump() -> None:
    """Pretty-print the full build config to stdout."""
    import pprint

    pprint.pprint(get())
